@startuml


participant Main
participant ":Game"
participant ":Gamecontroller"
participant ":Player"
participant ":Board"
participant ":Die"


Main -> ":Game" : runs
":Game" -> ":Gamecontroller" : uses
":Gamecontroller" -> ":Player" : howManyPlayers
":Player" --> ":Gamecontroller" : returns2Players
loop no winner
":Gamecontroller" -> ":Die" : rollDice
":Die" --> ":Gamecontroller" : returnsDiceTotal
":Gamecontroller"-> ":Board" : getFieldInfo
":Board" --> ":Gamecontroller" : returnsFieldInfo
":Gamecontroller"--> ":Game" : printsPlayerScore
alt DiceTotal != 10
":Gamecontroller" -> ":Gamecontroller" : switchPlayer
end
end
":Gamecontroller" --> ":Game" : returnsWinner
":Game" --> Main : printsWinner

@enduml