@startuml


participant Main
participant Game
participant Gamecontroller
participant Player
participant Board
participant Die


Main -> Game : runs
loop no winner
Game -> Gamecontroller : uses
Gamecontroller -> Player : whichPlayer
Player --> Gamecontroller : Player1or2
loop DiceTotal = 10
Gamecontroller -> Die : rollDice
Die --> Gamecontroller : returnsDiceTotal
Gamecontroller -> Board : getFieldInfo
Board --> Gamecontroller : returnsFieldInfo
Gamecontroller --> Game : printsPlayerScore
end
end
Gamecontroller --> Game : returnsWinner
Game --> Main : printsWinner

@enduml